const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  EFFACE_ITEM_FROM_CART: 'EFFACE_ITEM_FROM_CART'
};

export default CartActionTypes;
