const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
  PERSIST_USER_SESSION: 'PERSIST_USER_SESSION'

};

export default UserActionTypes;